import { QnaPostDetailResponse } from '@/types/community/qna';

export const dummyPostDetails: QnaPostDetailResponse[] = [
  {
    id: 1,
    author: { username: "alice", nickname: "Alice", profileImage: null },
    title: "React에서 useEffect는 언제 호출되나요?",
    content: "useEffect가 호출되는 시점과 의존성 배열의 의미를 알고 싶어요.",
    answerCount: 2,
    accepted: false,
    createdAt: "2025-10-25T09:30:00",
    answers: [
      {
        id: 11,
        postId: 1,
        author: { username: "david", nickname: "David", profileImage: null },
        content: "의존성 배열이 비어있으면 마운트 시 한 번만 호출됩니다.",
        likeCount: 3,
        accepted: false,
        liked: false,
        createdAt: "2025-10-25T10:00:00",
      },
      {
        id: 12,
        postId: 1,
        author: { username: "eve", nickname: "Eve", profileImage: null },
        content: "값이 바뀔 때마다 호출되는 점도 기억하세요.",
        likeCount: 1,
        accepted: false,
        liked: true,
        createdAt: "2025-10-25T10:20:00",
      },
    ],
  },
  {
    id: 2,
    author: { username: "bob", nickname: "Bob", profileImage: null },
    title: "TypeScript에서 타입을 확장하는 방법?",
    content: "인터페이스 상속과 타입 별칭의 차이를 알고 싶습니다.",
    answerCount: 1,
    accepted: false,
    createdAt: "2025-10-24T14:15:00",
    answers: [
      {
        id: 21,
        postId: 2,
        author: { username: "frank", nickname: "Frank", profileImage: null },
        content: "interface 상속은 여러 인터페이스를 확장할 수 있고, 타입 별칭은 union, intersection이 가능합니다.",
        likeCount: 2,
        accepted: false,
        liked: true,
        createdAt: "2025-10-24T15:00:00",
      },
    ],
  },
  {
    id: 3,
    author: { username: "carol", nickname: "Carol", profileImage: null },
    title: "React Native에서 FlatList 최적화 방법",
    content: "FlatList 렌더링 최적화와 keyExtractor 사용법을 알고 싶어요.",
    answerCount: 0,
    accepted: false,
    createdAt: "2025-10-23T11:45:00",
    answers: [],
  },
];